# Load OS specific config file
platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
    platform='linux'
elif [[ "$unamestr" == 'Darwin' ]]; then
    platform='mac'
fi

if [[ "$platform" == 'mac' ]]; then
    source "$HOME/.mac_bashrc"
fi
if [[ "$platform" == 'linux' ]]; then
    source "$HOME/.linux_bashrc"
fi
